# Generated by Django 3.0.7 on 2020-07-26 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CV',
            new_name='CVSection',
        ),
    ]
