# Generated by Django 3.0.7 on 2020-07-28 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200726_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My CV', max_length=200)),
                ('first_section', models.CharField(default='Personal Profile', max_length=200)),
                ('first_section_text', models.TextField()),
                ('second_section', models.CharField(default='Education', max_length=200)),
                ('second_section_text', models.TextField()),
                ('third_section', models.CharField(default='Technical Skills', max_length=200)),
                ('third_section_text', models.TextField()),
                ('fourth_section', models.CharField(default='Key Skills', max_length=200)),
                ('fourth_section_text', models.TextField()),
                ('fifth_section', models.CharField(default='Experience', max_length=200)),
                ('fifth_section_text', models.TextField()),
                ('sixth_section', models.CharField(default='Projects', max_length=200)),
                ('sixth_section_text', models.TextField()),
                ('seventh_section', models.CharField(default='Interest/Hobbies', max_length=200)),
                ('seventh_section_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CVSection',
        ),
    ]
