# Generated by Django 3.0.7 on 2020-08-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200728_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='author',
        ),
    ]
