# Generated by Django 3.0.7 on 2020-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_cv_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='fifth_section',
            field=models.CharField(blank=True, default='Experience', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='fifth_section_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='first_section',
            field=models.CharField(blank=True, default='Personal Profile', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='first_section_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='fourth_section',
            field=models.CharField(blank=True, default='Key Skills', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='fourth_section_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='second_section',
            field=models.CharField(blank=True, default='Education', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='second_section_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='seventh_section',
            field=models.CharField(blank=True, default='Interest/Hobbies', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='seventh_section_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='sixth_section',
            field=models.CharField(blank=True, default='Projects', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='sixth_section_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='third_section',
            field=models.CharField(blank=True, default='Technical Skills', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='third_section_text',
            field=models.TextField(blank=True),
        ),
    ]
